# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='useremail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
