# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('created', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='projectapp.Course')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
