# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_course_studentenrollcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollcourse',
            old_name='student_id',
            new_name='studentenroll_id',
        ),
    ]
